name: Build Develop

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1

    - name: Set up JDK 
      uses: actions/setup-java@v4.1.0
      distribution: adopt

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run Kover
      run: ./gradlew koverXmlReport

    - name: Upload Coverage to CodeCov
      uses: codecov/codecov-action@v4.1.0
      with:
        files: ./build/reports/kover/report.xml
        fail_ci_if_error: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
